# Generated by Django 4.2.5 on 2023-10-09 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_compass_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(through='club_compass_app.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
